name: React App Build

on:
  push:
    branches:
      - main  # mainブランチに変更があったときに実行

jobs:
  build:
    runs-on: ubuntu-24.04  # ubuntu-latestがubuntu-24.04に更新されるので、そのまま新しいバージョンを指定

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4  # v4にアップデート
      with:
        name: build
        path: build

    # `react-app`フォルダにビルドファイルをコピー
    - name: Copy build files to react-app
      run: |
        rm -rf react-app/*  # react-appフォルダを空にする
        cp -r build/* react-app/  # buildフォルダの内容をreact-appにコピー

    # 変更をGitHubにコミット＆プッシュ
    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add react-app
        git commit -m "Update react-app with latest build"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
